name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (use your desired version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      # Step 3: Install pnpm globally (ensure pnpm is installed)
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Verify pnpm installation
      - name: Verify pnpm installation
        run: pnpm --version

      # Step 5: Install project dependencies using pnpm
      - name: Install dependencies
        run: pnpm install

      # Step 6: Run Prettier check
      - name: Run Prettier
        run: pnpm prettier --check "**/*.{js,ts,json,md}"

      # Step 7: Run ESLint
      - name: Run ESLint
        run: pnpm eslint .
